[settings]
idiomatic_version_file_enable_tools = ["ruby"]
ruby.compile = false

[tools]
fd = "latest"
herdr = "latest"
ruby = "latest"
neovim = "latest"
ripgrep = "latest"
bat = "latest"
eza = "latest"
fzf = "latest"
jq = "latest"
lazygit = "latest"
yazi = "latest"
zoxide = "latest"
github-cli = "latest"
delta = "latest"
