# Don't print a new line at the start of the prompt
add_newline = false
# Pipes ╰─ ╭─
# Powerline symbols                                     
# Wedges 🭧🭒 🭣🭧🭓
# Random noise 🬖🬥🬔🬗
# Cool stuff 󰜥   

# format = """
# $cmd_duration$username$hostname $directory $git_branch
# $character
# """
format = """
 $directory $git_branch$git_status
$character"""

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[  ](bold fg:blue)"
error_symbol = "[  ](bold fg:red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
style = "bg: cyan"
symbol = "󰘬"
truncation_length = 12
truncation_symbol = ""
format = "[](bold fg:cyan)[$symbol](bg:cyan fg:black)[ ](bold fg:cyan)[$branch(:$remote_branch)](bold fg:white)"

[git_commit]
commit_hash_length = 4
tag_symbol = " "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
format = "[$staged$modified$deleted$renamed$conflicted$untracked$stashed$ahead_behind](bold fg:white)"
ahead = " ↑${count}"
behind = " ↓${count}"
diverged = " ↕${count}"
conflicted = " ✖${count}"
untracked = " ?${count}"
stashed = " ≡${count}"
modified = " ~${count}"
staged = " +${count}"
renamed = " »${count}"
deleted = " -${count}"


[hostname]
ssh_only = false
format =  "[•$hostname](bg:cyan bold fg:black)[](bold fg:cyan)"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed green"

[time]
disabled = true
format = '🕙[\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "bold bg:cyan fg:black"
style_root = "red bold"
format = "[](bold fg:cyan)[$user]($style)"
disabled = false
show_always = true

[directory]
home_symbol = ""
read_only = "  "
style = "bg:green fg:black"
truncation_length = 6
truncation_symbol = "../"
format = '[](bold fg:green)[~](bold $style)[](bold fg:green)[ $path](bold fg:white)' 

[cmd_duration]
min_time = 0
format = '[](bold fg:yellow)[󰪢 $duration](bold bg:yellow fg:black)[](bold fg:yellow)'

