"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 3

[palette]
pink = "#c2c2c2"
closer = "p:os"
os = "#7B747B"
lavender = "#A79F9C"
blue = "p:os"

[[blocks]]
alignment = "left"
type = "prompt"

  [[blocks.segments]]
  foreground = "p:os"
  style = "plain"
  template = "{{.Icon}} "
  type = "os"

  [[blocks.segments]]
  foreground = "p:blue"
  style = "plain"
  template = "{{ .UserName }}@{{ .HostName }} "
  type = "session"

  [[blocks.segments]]
  foreground = "p:pink"
  style = "plain"
  template = "{{ .Path }} "
  type = "path"

    [blocks.segments.properties]
    style = "folder"

  [[blocks.segments]]
  foreground = "p:lavender"
  template = "{{ .HEAD }} "
  style = "plain"
  type = "git"

    [blocks.segments.properties]
    branch_icon = " "
    cherry_pick_icon = " "
    commit_icon = " "
    fetch_status = false
    fetch_upstream_icon = false
    merge_icon = " "
    no_commits_icon = " "
    rebase_icon = " "
    revert_icon = " "
    tag_icon = " "

  [[blocks.segments]]
  style = "plain"
  foreground = "p:closer"
  template = ""
  type = "text"
